import { Inter } from "next/font/google";
import "./globals.css";
import BottomNavBar from "../components/navigation";
import { GlobalContextProvider } from "../components/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <BottomNavBar/>
      < GlobalContextProvider  >
        {children}
      </ GlobalContextProvider >

        </body>
    </html>
  );
}
